#Copyright© 2022 Vishal Ahirwar.
from tkinter import END, Tk,Text,Entry,Button,Label,Canvas,PhotoImage
def InitManager():
    def save():
        _website=website.get()
        _email= email.get()
        _password=password.get()
        with open("pwd.enc","a") as file:
            file.write(f"{_website},{_email},{_password}\n")
            website.delete(0,END)
            password.delete(0,END)
            
    window=Tk()
    window.title("Your Personal Password Manager")
    window.config(padx=50,pady=50,bg="white")
    canvas =Canvas(height=200,width=200)
    logo_img=PhotoImage(file="../res/logo.png")
    canvas.create_image(100,100,image=logo_img)
    canvas.config(bg="white",highlightthickness=0)
    canvas.grid(column=1,row=0)
    Label(text="Website Url/Name:",bg="white",fg="black").grid(column=0,row=1)
    website=Entry(width=25,bg="white",fg="black")
    website.grid(column=1,row=1)
    email=Entry(width=25,bg="white",fg="black")
    email.grid(column=1,row=2)
    password=Entry(width=26,bg="white",fg="black")
    password.grid(column=1,row=3)
    btn_gen=Button(text="Generate Password",bg="white",fg="black",activebackground="black",activeforeground="white")
    btn_gen.grid(column=2,row=3)
    btn_save=Button(text="Save and Encrypt Password",bg="white",fg="black",activebackground="black",activeforeground="white",command=save)
    btn_save.grid(column=1,row=4)
    btn_search=Button(text="Search and Decrypt Password",bg="white",fg="black",activebackground="black",activeforeground="white")
    btn_search.grid(column=2,row=1)
    Label(text="copyright© 2022 vishal ahirwar.",bg="white",fg="black").grid(column=0,row=6)
    Label(text="Email/Username:",bg="white",fg="black").grid(column=0,row=2)
    Label(text="Password:",bg="white",fg="black").grid(column=0,row=3)
    window.mainloop()
